# Generated by Django 3.0.3 on 2020-03-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials_title', models.CharField(max_length=200)),
                ('materials_content', models.TextField()),
                ('materials_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
