# Generated by Django 3.0.3 on 2020-03-14 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200314_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='materials_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 21, 10, 30, 69117), verbose_name='date published'),
        ),
    ]
