# Generated by Django 3.0.3 on 2020-03-14 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200314_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='materials_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 21, 12, 13, 472152), verbose_name='date published'),
        ),
    ]
