# Generated by Django 3.0.3 on 2020-04-16 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200316_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='materials_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 15, 58, 46, 995939), verbose_name='date published'),
        ),
    ]
